### ISSUE TITLE
请教一下 pnpm 安装 workspace : * 版本的命令

### ISSUE THREAD

**Issue by Silence-dream** [liuweiGL/pnpm-workspace#1]
[    "@formily/path": "workspace:*",](https://github.com/liuweiGL/pnpm-workspace/blob/02ae9983a4063903f955f80e5ff39d290d218fe6/packages/shared/package.json#L24)

你好,我想问一下 pnpm workspace 安装本地依赖,例如我安装的是这个本地的库

@formily/path 那么我应该在我想要安装的目录下执行
```shell
pnpm add @formily/path 
```
之后就如下所示,成了     "@formily/path": "^2.2.20",
<img width="862" alt="image" src="https://user-images.githubusercontent.com/42824008/223654486-3edc5d80-b864-4112-9e9a-3e8c9a156205.png">

如果执行
```shell
pnpm add ../path 
```
则如下所示
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/42824008/223654754-4466d454-eafe-42cf-99fe-7f61380399b9.png">

请问我要如何执行命令才能是"@formily/path": "workspace:*" 这样的形式?
难道只能手写进入然后再 pnpm i 吗?

**Comment by liuweiGL** [comment]
pnpm-workspace.yml 配置好，比如
```yml
packages:
  - 'packages/*'
```
然后执行
```shell
pnpm --filter @formily/core add @formily/path@*
```

**Comment by Silence-dream** [comment]
这样配置好好像并不能正确运行
```shell
pnpm --filter @formily/core add @formily/path@*
```
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/42824008/223737255-269aa91e-20cd-4da6-bb5d-3ebd2be49113.png">

**Comment by Silence-dream** [comment]
> pnpm-workspace.yml 配置好，比如
> 
> ```yaml
> packages:
>   - 'packages/*'
> ```
> 
> 然后执行
> 
> ```shell
> pnpm --filter @formily/core add @formily/path@*
> ```

这样配置好好像并不能正确运行
```shell
pnpm --filter @formily/core add @formily/path@*
```
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/42824008/223737255-269aa91e-20cd-4da6-bb5d-3ebd2be49113.png">

**Comment by liuweiGL** [comment]
我在 windows 系统使用 cmd 是正常的，你可以尝试：
1. 用双引号包起来再试试：`"@formily/path@*"`
2. 改用操作系统自带的 terminal 执行

**Comment by liuweiGL** [comment]
**还有使用 `--filter` 语法之后在项目根目录执行即可**

**Comment by Silence-dream** [comment]
成了但是这样安装到的是npm上的
```sh
pnpm --filter @formily/core add "@formily/path@*"
```
![image](https://user-images.githubusercontent.com/42824008/223746400-edb7c9d1-dc7c-457a-b1f3-253859434aae.png)

我限定为 workspack 下的依赖之后就成了这样
```sh
 pnpm --filter @formily/core add "@formily/path@*" --workspace
```
![image](https://user-images.githubusercontent.com/42824008/223747904-dc958a41-bbd0-4e54-856b-645c7b6160c5.png)

距离  workspace:* 这样的形式还差一步

**Comment by liuweiGL** [comment]
看看 pnpm 是不是最新版本的

**Comment by Silence-dream** [comment]
我换了两个pnpm的版本一个是 6.34.0一个是 7.29.1 都是一样的结果

![image](https://user-images.githubusercontent.com/42824008/223751550-7199060a-b19e-4ba7-8157-9996a12ca136.png)

**Comment by liuweiGL** [comment]
看下文档 https://pnpm.io/zh/next/npmrc#save-workspace-protocol
